### ISSUE TITLE
how to set the page orientation to landscape 

### ISSUE THREAD

**Issue by sheneeb** [aFelipeSP/pdfme#14]
in the pdf class the rotate_page is there to invert the page, how can i make the page landscape ?

**Comment by dwgillies** [comment]
I am not the developer but I'm looking to do the same thing.  It looks like you would just adjust the page size to swap the width and height of the paper.  The module where this happens (it has a table of paper sizes) is here.  Instead of a paper typeName, you can pass a tuple, i think.

https://github.com/aFelipeSP/pdfme/blob/main/pdfme/utils.py#L55
