### ISSUE TITLE
page break if the table row data crosses to next page and start the same row on the next page

### ISSUE THREAD

**Issue by sheneeb** [aFelipeSP/pdfme#22]
Hi 
I am using the pandas dataframe to generate a table data. Some Rows content is big it doesnt fit in the current page and part of it is gone to the second page, is there a way we can apply page break after the previous row and then the next row starts as a new page so that that whole row fits in the new page ?

**Comment by aFelipeSP** [comment]
Hi Sheeneb,
I think you can achieve this by creating a table for each row in the pandas dataframe, and embedding each table in a group element (These group elements guarantee that all of its elements will be in the same page. For more information about group elements check https://pdfme.readthedocs.io/en/latest/modules/content.html#module-pdfme.content)
You have to be carefull though, you have to be sure the contents of the group element (in this case the row table) will fit in the page, because group elements are not allowed to add more pages to keep adding its contents to the document, so it will raise an error if its contents don't fit. Something like this would work:

```python
...
{
    "group": [
        {
            'widths': [1.5, 1, 1, 1],
            'table': [
                table_row
            ]
        }
    ]
}
...
```
